# Generated by Django 5.1.3 on 2024-11-20 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Judgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(db_index=True, max_length=120, unique=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('date_added', models.DateField()),
                ('content', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('active', models.BooleanField(default=True, help_text='Scrape daily?')),
            ],
        ),
        migrations.CreateModel(
            name='JudgmentScrapeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('case_id', models.CharField(blank=True, max_length=120, null=True)),
                ('judgment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrape_events', to='judgments.judgment')),
            ],
        ),
    ]
