# Generated by Django 5.1.3 on 2024-11-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgment',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
