# Generated by Django 5.1.3 on 2024-11-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgments', '0003_alter_judgment_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgment',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
