# Generated by Django 5.1.3 on 2024-11-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgments', '0004_judgment_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgment',
            name='category',
            field=models.CharField(blank=True, choices=[('judgments', 'Judgments'), ('court_cases', 'Court Cases'), ('articles', 'Articles'), ('laws', 'Laws')], default='judgments', max_length=50, null=True),
        ),
    ]
